# ADP 24회  복기
## 1. 결석일수 회귀분석 문제
(설명변수) 1. sex, 2. age, 3. Pstatus, 4. Medu, 5. Fedu, 6. guardian, 7. traveltime, 8. studytime, 9. failures, 10. famrel, 11. freetime.   
(종속변수) 12. absences

### 1-1-1. EDA 하시오 (시각화 포함)
### 1-1-2. 전처리 하시오 (시각화 포함)
### 1-1-3. 여기에 하지 않았지만 추가할 수 있는 전처리를 하시고, 타당한 이유와 기대효과를 쓰세요.

### 1-2-1. 적용 가능한 알고리즘 3개 언급하고, 그 중 2개를 선택한 이유를 논리적으로 설명하세요. 
### 1-2-2. 모델 성능 평가 지표를 뭘로 쓸건지, 그 이유는 뭔지 쓰세요.
### 1-2-3. 2개 알고리즘을 실제로 프로그래밍하고 성능 평가를 시각화 통해 비교하고 설명하세요.

### 1-3-1. 실제로 사용가능한 모델인지 설명해보세요.
### 1-3-2. 다양한 환경에서 적용할 수 있는 방안을 설명해보세요.
### 1-3-3. 추가적으로 모델을 개선할 수 있는 방안을 설명해보세요.

In [ ]:
from pandas import read_csv
read_csv('student-mat.csv', sep=';')

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

## 2. 연구개발비(X1) : 1 2 3 4 5 7 8 9 11 12, 광고비(X2) : (낮음, 낮음, 낮음, 낮음, 높음, 높음, 높음, 높음, 높음, 높음), 매출액(Y) : 15 16 17 18 20 22 24 26 28 29
### 2-1. 광고비를 가변수화 해서, 다중선형회귀방정식 만들고, 회귀계수 검정하시오. 
### 2-2. 회귀 모형을 검정하시오.

## 3. 각각 표본수는 12개인데 A생산라인에서 만든 제품의 평균은 5.75mm, $\sigma = 0.03$ B생산라인에서 만든 제품의 평균은 5.56mm, $\sigma = 0.04$라면 5% 유의수준으로 두 제품의 평균이 차이가 있는지 여부를 검정하시오. Z(0.05) = 1.65.
### 3-1. 귀무가설과 대립가설을 세우기
### 3-2. 차이가 있는지 여부 검정

## 4. 베이지안 분류 문제: 바이러스 감염 분류표를 보고 베이지안 분류 방법으로, 양성으로 예측된 사람이 실제로 양성일 확률은? (유병률 0.01)

In [ ]:
from pandas import DataFrame
DataFrame([[370,10], [15, 690]], columns=['양성(실제)', '음성(실제)'], index=['양성(예측)', '음성(예측)'])

        양성(실제)  음성(실제)
양성(예측)     370      10
음성(예측)      15     690

In [ ]:
p(실제양성|양성예측) -> 사후분포
p(유병률) -> 모수 (베이지안 통계 알고싶어하는 것들)
p(양성예측|실제양성) -> likelihood 우도? 우도확률?

## 5.  9개 표본 [3.1, 3.3, 3.5, 3.7, 3.9, 4.1, 4.3 4.4, 4.7], 
one-sample t-test로 Z(0.05) = 1.65, Z(0.025) = ~, T(0.05, 8) = , T(0.025, 8) 
### 5-1. 위의 9개 표본의 평균에 대한 95% 신뢰구간?
### 5-2. 과거에 모집단 표준편차가 0.4일 때 표본 평균에 대한 95% 신뢰구간은?